# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: perfspect
  name: perfspect
  labels:
    app.kubernetes.io/name: perfspect
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: perfspect
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: perfspect
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: perfspect
        image: ptorre/perfspect
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.1
            memory: 1Gi
          limits:
            cpu: 0.1
            memory: 1Gi
        env:
        - name: Metrics
          value: "True"
#        securityContext:
#          runAsNonRoot: true
#          runAsUser: 10001
#          runAsGroup: 10001
#          allowPrivilegeEscalation: false
#          capabilities:
#            drop:
#              - ALL
#          seccompProfile:
#            type: RuntimeDefault
          #readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: perfspect
  namespace: perfspect
  labels:
    app.kubernetes.io/name: perfspect
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: perfspect
    app.kubernetes.io/component: backend
